// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAoq99G52XC-lYu7fJKQjqgZ_1qB_xqHE',
    appId: '1:536573147244:web:53e817e091745090ce8049',
    messagingSenderId: '536573147244',
    projectId: 'multi-vendor-stroe',
    authDomain: 'multi-vendor-stroe.firebaseapp.com',
    storageBucket: 'multi-vendor-stroe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD96INjImql7Re3RnW68Id3512WV5ZPbKI',
    appId: '1:536573147244:android:a7ae5c325938983fce8049',
    messagingSenderId: '536573147244',
    projectId: 'multi-vendor-stroe',
    storageBucket: 'multi-vendor-stroe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_NE-cvL_t918FJCvqfLjWURyuGRAXudE',
    appId: '1:536573147244:ios:6f3b7ff24c633f65ce8049',
    messagingSenderId: '536573147244',
    projectId: 'multi-vendor-stroe',
    storageBucket: 'multi-vendor-stroe.appspot.com',
    androidClientId: '536573147244-sjsjfc2ao8p7pem82odc7m74a6b7rubk.apps.googleusercontent.com',
    iosClientId: '536573147244-03abrj0jddv0ic81lqs96islitkib4co.apps.googleusercontent.com',
    iosBundleId: 'com.example.multivendor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_NE-cvL_t918FJCvqfLjWURyuGRAXudE',
    appId: '1:536573147244:ios:6f3b7ff24c633f65ce8049',
    messagingSenderId: '536573147244',
    projectId: 'multi-vendor-stroe',
    storageBucket: 'multi-vendor-stroe.appspot.com',
    androidClientId: '536573147244-sjsjfc2ao8p7pem82odc7m74a6b7rubk.apps.googleusercontent.com',
    iosClientId: '536573147244-03abrj0jddv0ic81lqs96islitkib4co.apps.googleusercontent.com',
    iosBundleId: 'com.example.multivendor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAoq99G52XC-lYu7fJKQjqgZ_1qB_xqHE',
    appId: '1:536573147244:web:576d5ee0e1ff54a5ce8049',
    messagingSenderId: '536573147244',
    projectId: 'multi-vendor-stroe',
    authDomain: 'multi-vendor-stroe.firebaseapp.com',
    storageBucket: 'multi-vendor-stroe.appspot.com',
  );
}
